### ISSUE TITLE
wrong instructions for Building and running on localhost

### ISSUE THREAD

**Issue by rezeau** [NDLA-H5P/h5p-timeline#403]
1.- npm install _throws lots of errors_, some but not all are fixed by running npm audit fix --force
2.- To create a production build: npm run build-prod should be: _npm run build_
3.- To create a development build: npm run build-dev should be _npm run build:dev_

**Comment by janlindso** [comment]
I should hopefully be working better now. Keep in mind you can also download the full library package under releases with all needed libraries.
I have also updated the instructions. Thanks for letting us know!
